name:                contract
version:             0.1.0.0
github:              "Krantz-XRF/contract"
license:             AGPL-3
author:              "Krantz-XRF"
maintainer:          "Krantz.XRF@outlook.com"
copyright:           "(c) Krantz 2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Krantz-XRF/contract#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
# Type level goodies
- ConstraintKinds
- DataKinds
- TypeOperators
# Type families
- TypeFamilies
# Deriving
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
# Flexible type classes
- FlexibleContexts
- FlexibleInstances
- QuantifiedConstraints
- MultiParamTypeClasses
# Type applications
- TypeApplications
- ScopedTypeVariables
# Pattern synonyms
- PatternSynonyms
# Grammar candies
- ViewPatterns
- LambdaCase
- TupleSections
- BangPatterns

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  contract-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contract

tests:
  contract-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - contract
